# URL de conexão com o banco de dados PostgreSQL, onde "localhost" é o servidor e "screensound_db" é o nome do banco de dados.
spring.datasource.url=jdbc:postgresql://localhost/screensound_db

# Nome de usuário utilizado para autenticar a conexão com o banco de dados PostgreSQL.
spring.datasource.username=SEU_USUARIO_AQUI

# Senha correspondente ao usuário do banco de dados.
spring.datasource.password=SUA_SENHA_AQUI

# Classe do driver JDBC que permite a conexão com o PostgreSQL.
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto do Hibernate, usado para traduzir as operações do JPA para a linguagem SQL do banco específico.
# HSQLDialect é um dialeto de exemplo, porém para PostgreSQL o correto seria usar `org.hibernate.dialect.PostgreSQLDialect`.
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Configuração do Hibernate para o JPA. O valor "update" faz com que o Hibernate atualize o esquema do banco de dados,
# criando tabelas ou alterando-as conforme necessário sem apagar dados existentes.
spring.jpa.hibernate.ddl-auto=update
